config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  namespace 'admin' do
    resources :sessions, only: [:new, :create, :destroy]
    get 'login', to: 'sessions#new', as: :login
    get 'logout', to: 'sessions#destroy', as: :logout
    root 'dashboard#index'
    resources :posts
    get "show_month", to: "days#show_month"
    get "month_up", to: "days#month_up"
    get "month_down", to: "days#month_down"
    resources :days
    resources :gratifications
    resources :greetings

    resources :push_notifications
    get "send_out_push_notification", to: "push_notifications#send_out"

  end

  namespace :api do
  ##POC routes no sessions
    namespace :v1 do
      resources :posts, only: [:index]
      resources :greetings, only: [:index]
      post "push_token", to: "tokens#create"
    end
  end
end

app/models/greeting.rb
class Greeting < ApplicationRecord
end

app/controllers/admin/greetings_controller.rb
class Admin::GreetingsController < Admin::AdminApplicationController

  def index
    ##only show the latest one?
    @greetings = Greeting.all
  end

  def show
    @current_greeting = Greeting.find(params["id"])
  end


  def new
    @greeting = Greeting.new
  end


  def create
    @greeting = Greeting.new greeting_params
    if @greeting.save
      redirect_to admin_greetings_path
    else
      render 'new'
    end
  end

  def edit
    @greeting = Greeting.find(params[:id])
  end

  def update
    @greeting = Greeting.find(params[:id])
    if @greeting.update(greeting_params)
      redirect_to admin_greetings_path
    else
      render 'edit'
    end
  end

  def destroy
    greeting = Greeting.find(params["id"])
    if greeting.destroy
      flash[:notice] = "Greeting successfully deleted"
      redirect_to admin_greetings_path
    else
      flash[:notice] = "Could not delete greeting"
      redirect_to admin_greetings_path
    end
  end





  private
    def greeting_params
      params.require(:greeting).permit(Greeting.column_names.map {|x| unless x == "id"; x.to_sym; end}.compact)
    end

end

app/controllers/api/v1/greetings_controller.rb
class Api::V1::GreetingsController < Api::ApiApplicationController
  # GET /greetings
  # GET /greetings.json
  def index
    ##only display last active greeting? active not set up yet
    @greeting = Greeting.last

  end


end

app/views/admin/greetings/_form.html.haml
.row
	/ left column
	.col-md-8
		/ general form elements
		.box.box-primary
			.box-header.with-border
				%h3.box-title New Greeting
			/ /.box-header
			/ form start
			%h3{:style => "padding: 10px;"}
				Greeting Details
			= simple_form_for [:admin, @greeting] do |f|
				.input-container{:style => "float: left; border: none; padding: 9px; outline: none; margin: 0 0 0 5px; font-family: os-regular; font-size: 20px; color: #000; font-weight: normal;"}
					%label
						Greeting Edition
					= f.input_field :edition, placeholder: '000', class: "form-control"
				.input-container{:style => "float: left; border: none; padding: 9px; outline: none; margin: 0 0 0 5px; font-family: os-regular; font-size: 20px; color: #000; font-weight: normal;"}
					%label
						Greeting Title
					= f.input_field :title, placeholder: 'Gratification Title', class: "form-control"
				.input-container.submit-btn-wrapper
					= f.submit "Submit", class: "submit-btn validate-form"

app/views/admin/greetings/edit.html.haml
/ Content Wrapper. Contains page content
.content-wrapper
  / Content Header (Page header)
  %section.content-header
    %h1
      Edit A Greeting

    %ol.breadcrumb
      %li
        %a{:href => admin_root_path}
          %i.fa.fa-dashboard
          Home
      %li
        %a{:href => admin_greetings_path} Greetings
      %li.active Edit
  / Main content
  %section.content#wizard-appendix
    = render 'form'

app/views/admin/greetings/index.html.haml
.content-wrapper
  / Content Header (Page header)
  %section.content-header
    %h1
      Greetings
      -# %small All New Now Posts
    %ol.breadcrumb
      %li
        %a{:href => admin_root_path}
          %i.fa.fa-dashboard
          Home
      %li.active
        %a{:href => admin_greetings_path}
          Gratifications
  / Main content
  %section.content
    .row
      .col-xs-12
        .box
          .box-header
            %h3.box-title All Greetings
            .box-tools
              %a{:href => new_admin_greeting_path}
                %button.btn.btn-sm.btn-default
                  %i.fa.fa-plus-circle
          .box-body.table-responsive.no-padding
            %table.table.table-hover{:style => "width: 100%;"}
              %tr
                %th Edition
                %th Title
              - @greetings.each do |greeting|
                %tr
                  %td= greeting.edition
                  %td= greeting.title
                  %td
                    %span= link_to "", edit_admin_greeting_path(greeting), class: 'btn fa fa-pencil'
                    %span= link_to "", admin_greeting_path(greeting), method: :delete, data: {confirm: "Are you sure?"}, class: 'btn fa fa-trash'

app/views/admin/greetings/new.html.haml
/ Content Wrapper. Contains page content
.content-wrapper
  / Content Header (Page header)
  %section.content-header
    %h1
      Add a New Greeting

    %ol.breadcrumb
      %li
        %a{:href => admin_root_path}
          %i.fa.fa-dashboard
          Home
      %li
        %a{:href => admin_greetings_path} Greetings
      %li.active New
  / Main content
  %section.content#wizard-appendix
    = render 'form'