config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  namespace 'admin' do
    resources :sessions, only: [:new, :create, :destroy]
    get 'login', to: 'sessions#new', as: :login
    get 'logout', to: 'sessions#destroy', as: :logout
    root 'dashboard#index'
    resources :posts
    get "show_month", to: "days#show_month"
    get "month_up", to: "days#month_up"
    get "month_down", to: "days#month_down"
    resources :days
    resources :gratifications
    resources :greetings

    resources :push_notifications
    get "send_out_push_notification", to: "push_notifications#send_out"

  end

  namespace :api do
  ##POC routes no sessions
    namespace :v1 do
      resources :posts, only: [:index]
      resources :greetings, only: [:index]
      post "push_token", to: "tokens#create"
    end
  end
end

app/models/gratification.rb
class Gratification < ApplicationRecord

    validates :message, :keyword, :image, :alternate_message, presence: true

    mount_uploader :image, ImageUploader

end

app/controllers/admin/gratifications_controller.rb
class Admin::GratificationsController < Admin::AdminApplicationController

  def index
    @gratifications = Gratification.all
  end

  def show
    @current_gratification = Gratification.find(params["id"])
  end


  def new
    @gratification = Gratification.new
  end


  def create
    @gratification = Gratification.new gratification_params
    if @gratification.save
      redirect_to admin_gratifications_path
    else
      render 'new'
    end
  end

  def edit
    @gratification = Gratification.find(params[:id])
  end

  def update
    @gratification = Gratification.find(params[:id])
    if @gratification.update(gratification_params)
      redirect_to admin_gratifications_path
    else
      render 'edit'
    end
  end

  def destroy
    gratification = Gratification.find(params["id"])
    if gratification.destroy
      flash[:notice] = "Gratification successfully deleted"
      redirect_to admin_gratifications_path
    else
      flash[:notice] = "Could not delete gratification"
      redirect_to admin_gratifications_path
    end
  end





  private
    def gratification_params
      params.require(:gratification).permit(Gratification.column_names.map {|x| unless x == "id"; x.to_sym; end}.compact)
    end

end

app/views/admin/gratifications/_form.html.haml
.row
	/ left column
	.col-md-8
		/ general form elements
		.box.box-primary
			.box-header.with-border
				%h3.box-title New Gratification
			/ /.box-header
			/ form start
			%h3{:style => "padding: 10px;"}
				Gratification Details
			= simple_form_for [:admin, @gratification] do |f|
				.input-container{:style => "float: left; border: none; padding: 9px; outline: none; margin: 0 0 0 5px; font-family: os-regular; font-size: 20px; color: #000; font-weight: normal;"}
					%label
						Gratification Title
					= f.input_field :title, placeholder: 'Gratification title', class: "form-control"
				.input-container{:style => "float: left; border: none; padding: 9px; outline: none; margin: 0 0 0 5px; font-family: os-regular; font-size: 20px; color: #000; font-weight: normal;"}
					%label
						Gratification Message
					= f.input_field :message, placeholder: 'Gratification message', class: "form-control"
				.input-container{:style => "float: left; border: none; padding: 9px; outline: none; margin: 0 0 0 5px; font-family: os-regular; font-size: 20px; color: #000; font-weight: normal;"}
					%label
						Gratification Search Term
					= f.input_field :keyword, placeholder: 'Gratification Keyword', class: "form-control"
				.input-container{:style => "float: left; border: none; padding: 9px; outline: none; margin: 0 0 0 5px; font-family: os-regular; font-size: 20px; color: #000; font-weight: normal;"}
					%label
						Button Label
					= f.input_field :button_label, placeholder: 'Gratification Button Label', class: "form-control"
				.input-container{:style => "float: left; border: none; padding: 9px; outline: none; margin: 0 0 0 5px; font-family: os-regular; font-size: 20px; color: #000; font-weight: normal;"}
					%label
						Alernate Message (if they don't provide location)
					= f.input_field :alternate_message, placeholder: 'Alternate Message', class: "form-control"
				.input-container{:style => "float: left; margin-left: 2em; padding-top: 1em; padding-bottom: 1em;"}
					%label
						Is Active?
					= f.input_field :active, as: :boolean, type: :checkbox, placeholder: 'Active', class: ""
				.div{:style => "clear: both"}
				.input-container{:style => "border: none; padding: 9px; outline: none; margin: 0 0 0 5px; font-family: os-regular; font-size: 20px; color: #000; font-weight: normal"}
					%label
						Background Image
					-if @gratification.image.portrait.url != nil
						%br
						=image_tag(@gratification.image.portrait.url)
						=f.file_field :image
						=f.hidden_field :image_cache
					-else
						=f.file_field :image
						=f.hidden_field :image_cache

				.input-container.submit-btn-wrapper
					= f.submit "Submit", as: :int, class: "submit-btn validate-form"

app/views/admin/gratifications/edit.html.haml
/ Content Wrapper. Contains page content
.content-wrapper
  / Content Header (Page header)
  %section.content-header
    %h1
      Edit A Gratification

    %ol.breadcrumb
      %li
        %a{:href => admin_root_path}
          %i.fa.fa-dashboard
          Home
      %li
        %a{:href => admin_gratifications_path} Gratifications
      %li.active Edit
  / Main content
  %section.content#wizard-appendix
    = render 'form'

app/views/admin/gratifications/index.html.haml
.content-wrapper
  / Content Header (Page header)
  %section.content-header
    %h1
      Gratifications
      -# %small All New Now Posts
    %ol.breadcrumb
      %li
        %a{:href => admin_root_path}
          %i.fa.fa-dashboard
          Home
      %li.active
        %a{:href => admin_gratifications_path}
          Gratifications
  / Main content
  %section.content
    .row
      .col-xs-12
        .box
          .box-header
            %h3.box-title All Gratifications
            .box-tools
              %a{:href => new_admin_gratification_path}
                %button.btn.btn-sm.btn-default
                  %i.fa.fa-plus-circle
          .box-body.table-responsive.no-padding
            %table.table.table-hover{:style => "width: 100%;"}
              %tr
                %th Title
                %th Message
                %th Search Term
                %th Button Label
                %th Active
              - @gratifications.each do |gratification|
                %tr
                  %td= gratification.title
                  %td= gratification.message
                  %td= gratification.keyword
                  %td= gratification.button_label
                  %td= gratification.active
                  %td
                    %span= link_to "", edit_admin_gratification_path(gratification), class: 'btn fa fa-pencil'
                    %span= link_to "", admin_gratification_path(gratification), method: :delete, data: {confirm: "Are you sure?"}, class: 'btn fa fa-trash'

app/views/admin/gratifications/new.html.haml
/ Content Wrapper. Contains page content
.content-wrapper
  / Content Header (Page header)
  %section.content-header
    %h1
      Add a New Gratification

    %ol.breadcrumb
      %li
        %a{:href => admin_root_path}
          %i.fa.fa-dashboard
          Home
      %li
        %a{:href => admin_gratifications_path} Gratifications
      %li.active New
  / Main content
  %section.content#wizard-appendix
    = render 'form'