config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  namespace 'admin' do
    resources :sessions, only: [:new, :create, :destroy]
    get 'login', to: 'sessions#new', as: :login
    get 'logout', to: 'sessions#destroy', as: :logout
    root 'dashboard#index'
    resources :posts
    get "show_month", to: "days#show_month"
    get "month_up", to: "days#month_up"
    get "month_down", to: "days#month_down"
    resources :days
    resources :gratifications
    resources :greetings

    resources :push_notifications
    get "send_out_push_notification", to: "push_notifications#send_out"

  end

  namespace :api do
  ##POC routes no sessions
    namespace :v1 do
      resources :posts, only: [:index]
      resources :greetings, only: [:index]
      post "push_token", to: "tokens#create"
    end
  end
end

app/models/push_notification.rb
class PushNotification < ApplicationRecord
end

app/controllers/admin/push_notifications_controller.rb
class Admin::PushNotificationsController < Admin::AdminApplicationController

  def index
    @push_notifications = PushNotification.all
  end

  def show
    @current_push_notification = PushNotification.find(params["id"])
  end


  def new
    @push_notification = PushNotification.new
  end


  def create
    @push_notification = PushNotification.new push_notification_params
    if @push_notification.save
      redirect_to admin_push_notifications_path
    else
      render 'new'
    end
  end

  def edit
    @push_notification = PushNotification.find(params[:id])
  end

  def update
    @push_notification = PushNotification.find(params[:id])
    if @push_notification.update(push_notification_params)
      redirect_to admin_push_notifications_path
    else
      render 'edit'
    end
  end

  def destroy
    push_notification = PushNotification.find(params["id"])
    if push_notification.destroy
      flash[:notice] = "Notification successfully deleted"
      redirect_to admin_push_notifications_path
    else
      flash[:notice] = "Could not delete notification"
      redirect_to admin_push_notifications_path
    end
  end


  def send_out
    @push_notification = PushNotification.find(params["format"])
    @tokens = Token.all
    @tokens.each do |token|
      push_alert = PushAlert.new(
        token: token,
        notification: "New Articles",
        alert: "#{@push_notification.message}!"
      )
      response = push_alert.create_notification
      Rails.logger.info response
    end
  end




  private
    def push_notification_params
      params.require(:push_notification).permit(PushNotification.column_names.map {|x| unless x == "id"; x.to_sym; end}.compact)
    end

end

app/views/admin/push_notifications/_form.html.haml
.row
	/ left column
	.col-md-8
		/ general form elements
		.box.box-primary{style: "height: 400px;"}
			.box-header.with-border
				%h3.box-title New Notification
			/ /.box-header
			/ form start
			%h3{:style => "padding: 10px;"}
				Notification Details
			= simple_form_for [:admin, @push_notification] do |f|
				.input-container{:style => "float: left; border: none; padding: 9px; outline: none; margin: 0 0 0 5px; font-family: os-regular; font-size: 20px; color: #000; font-weight: normal;"}
					%label
						Message
					= f.input_field :message, placeholder: '', class: "form-control"
				.input-container{:style => "float: left; border: none; padding: 9px; outline: none; margin: 0 0 0 5px; font-family: os-regular; font-size: 20px; color: #000; font-weight: normal;"}
					%label
					= f.input :active, as: :boolean, type: :checkbox, class: "form-control"
				.div{style: "clear: both"}
				.input-container.submit-btn-wrapper{style: "float: left;"}
					= f.submit "Submit", class: "submit-btn validate-form"

app/views/admin/push_notifications/edit.html.haml
/ Content Wrapper. Contains page content
.content-wrapper
  / Content Header (Page header)
  %section.content-header
    %h1
      Edit A Notification

    %ol.breadcrumb
      %li
        %a{:href => admin_root_path}
          %i.fa.fa-dashboard
          Home
      %li
        %a{:href => admin_push_notification_path} Push notifications
      %li.active Edit
  / Main content
  %section.content#wizard-appendix
    = render 'form'

app/views/admin/push_notifications/index.html.haml
.content-wrapper
  / Content Header (Page header)
  %section.content-header
    %h1
      Push Notifications
      -# %small All New Now Posts
    %ol.breadcrumb
      %li
        %a{:href => admin_root_path}
          %i.fa.fa-dashboard
          Home
      %li.active
        %a{:href => admin_push_notifications_path}
          Notifications
  / Main content
  %section.content
    .row
      .col-xs-12
        .box
          .box-header
            %h3.box-title Tip - Sending to users takes about 2 seconds per Device.  The page is not stuck, it just takes a while.   
            .box-tools
              %a{:href => new_admin_push_notification_path}
                %button.btn.btn-sm.btn-default
                  %i.fa.fa-plus-circle
          .box-body.table-responsive.no-padding
            %table.table.table-hover{:style => "width: 100%;"}
              %tr
                %th Message
                %th Active
                %th Send to Users
                %th Edit
                %th Delete
              - @push_notifications.each do |notification|
                %tr
                  %td= notification.message
                  %td= notification.active
                  %td
                    %span= link_to "", admin_send_out_push_notification_path(notification), class: 'btn fa fa-rocket'
                  %td
                    %span= link_to "", edit_admin_push_notification_path(notification), class: 'btn fa fa-pencil'
                  %td
                    %span= link_to "", admin_push_notification_path(notification), method: :delete, data: {confirm: "Are you sure?"}, class: 'btn fa fa-trash'

app/views/admin/push_notifications/new.html.haml
/ Content Wrapper. Contains page content
.content-wrapper
  / Content Header (Page header)
  %section.content-header
    %h1
      Add a New Notification

    %ol.breadcrumb
      %li
        %a{:href => admin_root_path}
          %i.fa.fa-dashboard
          Home
      %li
        %a{:href => admin_push_notifications_path} Notifications
      %li.active New
  / Main content
  %section.content#wizard-appendix
    = render 'form'