config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  namespace 'admin' do
    resources :sessions, only: [:new, :create, :destroy]
    get 'login', to: 'sessions#new', as: :login
    get 'logout', to: 'sessions#destroy', as: :logout
    root 'dashboard#index'
    resources :posts
    get "show_month", to: "days#show_month"
    get "month_up", to: "days#month_up"
    get "month_down", to: "days#month_down"
    resources :days
    resources :gratifications
    resources :greetings

    resources :push_notifications
    get "send_out_push_notification", to: "push_notifications#send_out"

  end

  namespace :api do
  ##POC routes no sessions
    namespace :v1 do
      resources :posts, only: [:index]
      resources :greetings, only: [:index]
      post "push_token", to: "tokens#create"
    end
  end
end

app/models/day.rb
class Day < ApplicationRecord

  has_many :posts


  def number_of_posts
    self.posts.count
  end

  def get_posts
    posts = self.posts.to_a
    id = self.id
    ##take position into account
    while posts.count < 7
      ##get posts from previous day
      previous_day_posts = Post.where(day_id: (id - 1))
      sorted_posts = previous_day_posts.sort_by {|post| post.position}

      count = posts.count
      if previous_day_posts != []
        sorted_posts.each do |post|
          post.position = count +=1
          posts.append(post)
        end
      end
      ##chance there are still not enough posts
      id = id - 1
    end
    ##only return first 7 if there are more
    return posts[0, 7]
  end

  def self.today
    return Day.find_by_date(Date.today)
  end


end

app/controllers/admin/days_controller.rb
class Admin::DaysController < Admin::AdminApplicationController
  def index
    today = Day.where(date: Date.today).last
    first_day = Date.civil(Date.today.year, Date.today.month, 1)
    last_day = Date.civil(Date.today.year, Date.today.month, -1)
    # @days = Day.include("date").where("date BETWEEN (?) AND (?)", today.date - 30.days, today.date + 30.days)
    @month = Date.today.strftime("%B %Y")
    @month_number = Date.today.month
    @year_number = Date.today.year
    @days = Day.where("date BETWEEN (?) AND (?)", first_day, last_day)
    @days = @days.sort_by{|day| day.date }
  end

  def show
    @current_day = Day.find(params["id"])
    @posts = @current_day.posts
  end


  def month_down
    old_month_number = params["month"].to_i
    old_year_number = params["year"].to_i
    last_month_full_date = Date.civil(old_year_number, old_month_number).last_month

    @month_number = last_month_full_date.month
    @year_number = last_month_full_date.year
    @month = last_month_full_date.strftime("%B %Y")
    today = Day.where(date: Date.today).last
    first_day = Date.civil(@year_number, @month_number, 1)
    last_day = Date.civil(@year_number, @month_number, -1)
    # @days = Day.include("date").where("date BETWEEN (?) AND (?)", today.date - 30.days, today.date + 30.days)
    # @month = Date.today.strftime("%B %Y")
    # @month_number = Date.today.month
    # @year_number = Date.today.year
    if self.check_past_days(first_day, last_day) == false
      return false
    else
      @days = Day.where("date BETWEEN (?) AND (?)", first_day, last_day)
      @days = @days.sort_by{|day| day.date }

    end



  end


  def month_up

    Rails.logger.info "What is month from JS Listener #{params["month"].to_i}"
    Rails.logger.info "What is year from JS Listener #{params["year"].to_i}"



    old_month_number = params["month"].to_i
    old_year_number = params["year"].to_i
    next_month_full_date = Date.civil(old_year_number, old_month_number).next_month
    @month_number = next_month_full_date.month
    @year_number = next_month_full_date.year
    @month = next_month_full_date.strftime("%B %Y")
    today = Day.where(date: Date.today).last
    first_day = Date.civil(@year_number, @month_number, 1)
    last_day = Date.civil(@year_number, @month_number, -1)
    # @days = Day.include("date").where("date BETWEEN (?) AND (?)", today.date - 30.days, today.date + 30.days)
    # @month = Date.today.strftime("%B %Y")
    # @month_number = Date.today.month
    # @year_number = Date.today.year
    self.check_days(first_day, last_day)
    @days = Day.where("date BETWEEN (?) AND (?)", first_day, last_day)
    @days = @days.sort_by{|day| day.date }


  end


  def check_days first_day, last_day
    ##check to see if we have these days created
    start_date = first_day
    last_day = last_day
    while start_date <= last_day do
      if Day.find_by_date(start_date) != nil
        ##there is a day created already so don't make another one
      else
        ##this day has not been created so make it
        return false
      end
      start_date = start_date + 1.days
    end
  end

  def check_past_days first_day, last_day
    start_date = first_day
    if Day.find_by_date(start_date) == nil
      return false
    else
      return true
    end

  end

  private

end

app/views/admin/days/_days_list.html.haml
%section.content
  .row
    .col-xs-12
      .box
        .box-header
          %span#month-down{data: {month: @month_number, year: @year_number}}= link_to "", "", class: 'btn fa fa-arrow-circle-left fa-2x'

          %h3.box-title#month-date
            =@month
          %span#month-up{data: {month: @month_number, year: @year_number}}= link_to "", "", class: 'btn fa fa-arrow-circle-right fa-2x'
          -# .box-tools
          -#   .input-group{:style => "width: 150px;"}
          -#     -# %input.form-control.input-sm.pull-right{:name => "table_search", :placeholder => "Search", :type => "text"}
          -#       .input-group-btn
          -#         %button.btn.btn-sm.btn-default
          -#           %i.fa.fa-search= link_to "", admin_greetings_path
        / /.box-header
        .box-body.table-responsive.no-padding
          %table.table.table-hover{:style => "width: 100%;"}
            %tr
              %th Date
              %th Number of Posts
            - @days.each do |day|
              - if day.date == Date.today
                %tr{style: "background-color: lightblue;"}
                  %td= day.date.strftime("%B %d, %Y")
                  %td= day.number_of_posts
                  %td
                    %span= link_to "", admin_day_path(day), class: 'btn fa fa-pencil'
              -else
                %tr
                  %td= day.date.strftime("%B %d, %Y")
                  %td= day.number_of_posts
                  %td
                    %span= link_to "", admin_day_path(day), class: 'btn fa fa-pencil'

app/views/admin/days/index.html.haml
.content-wrapper
  / Content Header (Page header)
  %section.content-header
    %h1
      Days
      -# %small All New Now Posts
    -# %ol.breadcrumb
    -#   %li
    -#     %a{:href => admin_root_path}
    -#       %i.fa.fa-dashboard
    -#       Home
    -#   %li.active
    -#     %a{:href => admin_days_path}
    -#       Days
  / Main content
  #day_list
    = render "days_list"
  -# %section.content
  -#   .row
  -#     .col-xs-12
  -#       .box
  -#         .box-header
  -#           %span#month-down{data: {month: @month_number, year: @year_number}}= link_to "", "", class: 'btn fa fa-arrow-circle-left fa-2x'
  -#
  -#           %h3.box-title#month-date
  -#             =@month
  -#           %span#month-up{data: {month: @month_number, year: @year_number}}= link_to "", "", class: 'btn fa fa-arrow-circle-right fa-2x'
  -#           -# .box-tools
  -#           -#   .input-group{:style => "width: 150px;"}
  -#           -#     -# %input.form-control.input-sm.pull-right{:name => "table_search", :placeholder => "Search", :type => "text"}
  -#           -#       .input-group-btn
  -#           -#         %button.btn.btn-sm.btn-default
  -#           -#           %i.fa.fa-search= link_to "", admin_greetings_path
  -#         / /.box-header
  -#         .box-body.table-responsive.no-padding#day_list
            -# %table.table.table-hover{:style => "width: 100%;"}
            -#   %tr
            -#     %th Date
            -#     %th Number of Posts
            -#   - @days.each do |day|
            -#     - if day.date == Date.today
            -#       %tr{style: "background-color: lightblue;"}
            -#         %td= day.date.strftime("%B %d, %Y")
            -#         %td= day.number_of_posts
            -#         %td
            -#           %span= link_to "", admin_day_path(day), class: 'btn fa fa-pencil'
            -#     -else
            -#       %tr
            -#         %td= day.date.strftime("%B %d, %Y")
            -#         %td= day.number_of_posts
            -#         %td
            -#           %span= link_to "", admin_day_path(day), class: 'btn fa fa-pencil'

app/views/admin/days/month_down.js.erb
$("#day_list").html("")
$("#day_list").html("<%= j render :partial => 'days_list', :locals => {:@days => @days, :@month_number => @month_number, :@year_number => @year_number, :@month => @month}%>")

app/views/admin/days/month_up.js.erb
// $("#day_list").html("")
$("#day_list").html("<%= j render :partial => 'days_list', :locals => {:@days => @days, :@month_number => @month_number, :@year_number => @year_number, :@month => @month}%>")

app/views/admin/days/show.html.haml
.content-wrapper
  / Content Header (Page header)
  %section.content-header
    %h1
      ="Posts for #{@current_day.date.strftime("%B %d, %Y")}"
      -# %small All New Now Posts
    -# %ol.breadcrumb
    -#   %li
    -#     %a{:href => admin_root_path}
    -#       %i.fa.fa-dashboard
    -#       Home
    -#   %li.active
    -#     %a{:href => admin_days_path}
    -#       Days
  / Main content
  %section.content
    .row
      .col-xs-12
        .box
          .box-header
            %h3.box-title

            .box-tools
              %a{:href => new_admin_post_path(day: @current_day)}
                %button.btn.btn-sm.btn-default
                  %i.fa.fa-plus-circle New Post
              -# .input-group{:style => "width: 150px;"}
              -#   %input.form-control.input-sm.pull-right{:name => "table_search", :placeholder => "Search", :type => "text"}
              -#     .input-group-btn
              -#       %button.btn.btn-sm.btn-default
              -#         %i.fa.fa-search
          / /.box-header
          .box-body.table-responsive.no-padding
            %table.table.table-hover{:style => "width: 100%;"}
              %tr
                -# %th Headline
                %th Body
                %th Image
                %th Position

              - @posts.each do |post|
                %tr
                  -# %td= post.headline
                  %td= post.body
                  %td= image_tag(post.image.thumb.url)
                  %td= post.position
                  %td
                    %span= link_to "", edit_admin_post_path(post), class: 'btn fa fa-pencil'
                    %span= link_to "", admin_post_path(post), method: :delete, data: {confirm: "Are you sure?"}, class: 'btn fa fa-trash'